FROM --platform=linux/arm/v7 debian:trixie

RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    curl \
    git \
    meson \
    ninja-build \
    libportaudio2 \
    portaudio19-dev \
    libasound2-dev \
    libclang-dev \
    clang

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /build